config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'homepage#index'
  get 'homepage#index/:uuid' => 'homepage#index'

  # match "/patients/:id" => "patients#show"
  #
  # get 'homepage#index/:uuid' => 'homepage#index', :as => :root

  resources :games
  resources :players

  namespace :api do
    post 'events', to: 'events#receive_events'
  end

  post 'rolls', to: 'dices#rolls'
  post 'start_a_game', to: 'games#start_a_game'
  post 'end_game', to: 'games#end_game'

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!


  def index
    # @user = User.first
    # Create a games or Join a games with a code

    redirect_to @user.current_game if user_signed_in? && @user.present? && @user.players.present? && @user.current_game.status != Game::FINISHED
  end


  private

  def set_user
    # params[:uuid] = '072e69bc-c51a-11eb-8529-0242ac130003' if Rails.env.development?
    puts "received uuid : #{params[:uuid]}"
    uuid = params[:uuid].split('!').first
    puts "modified uuid : #{uuid}"
    @user = User.where(fidmarques_uuid: uuid).first
    sign_in @user, event: :authentication if !user_signed_in? || @user.present?
  end
end

app/views/homepage/index.html.erb
Bonjour <%= current_user.name %>, <br />
Bienvenue dans notre jeu de l'Oie, vous vous apprêtez à jouer au meilleur jeu au monde !  <br />

<%= link_to "Créer une partie",  games_path, method: :post, class: "btn btn-primary mb-3" %> <br />
<%= link_to "Rejoindre une partie",  new_player_path, class: "btn btn-warning" %>