config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'homepage#index'
  get 'homepage#index/:uuid' => 'homepage#index'

  # match "/patients/:id" => "patients#show"
  #
  # get 'homepage#index/:uuid' => 'homepage#index', :as => :root

  resources :games
  resources :players

  namespace :api do
    post 'events', to: 'events#receive_events'
  end

  post 'rolls', to: 'dices#rolls'
  post 'start_a_game', to: 'games#start_a_game'
  post 'end_game', to: 'games#end_game'

end

app/models/game.rb
class Game < ApplicationRecord
  AVAILABLE_COLORS = ['VERT', 'ROUGE', 'BLEU', 'JAUNE']
  WAITING = 'WAITING'
  RUNNING = 'RUNNING'
  FINISHED = 'FINISHED'

  has_many :players, dependent: :destroy
  has_many :spaces, dependent: :destroy
  has_many :game_credits, dependent: :destroy

  has_many :player_space_positions, dependent: :destroy


  def color_available
    AVAILABLE_COLORS - players.pluck(:color)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!

  before_action :set_game, only: [:show, :start_a_game, :end_game]
  def show
    @player = Player.where(user: current_user, game: @game).first_or_initialize
    @board = @game.spaces.order(position: :asc)
    @players = @game.players
    @credits = GameCredit.where(game:@game, personable: current_user.current_player_or_user, is_used: nil).last if @players.present?
    @positions = @game.player_space_positions
    @finished = @positions.map{|position| position.space.position}.include?(63)
  end

  def create

    @game = Game::CreateAGame.run!(user: current_user)
    # game_current_user = Game.where(user_id: current_user.id).last
    if @game.present?
      redirect_to @game
    else
      redirect_to root_path
    end

  end

  def join
    @user = User.find(params)
  end

  def start_a_game
    Game::StartAGame.run!(game: @game)
    redirect_to @game
  end

  def end_game
    @game.update(status: Game::FINISHED)
    redirect_to root_path(uuid: current_user.fidmarques_uuid)
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end
end

app/helpers/game_helper.rb
module GameHelper

  def display_icon(space_skill_id)

    if space_skill_id == 1
      'square'
    elsif space_skill_id == 2
      'square_two_times'
    elsif space_skill_id == 3
      'square_move_back_3_cases'
    elsif space_skill_id == 4
      'square_hole'
    elsif space_skill_id == 5
      'square_bump'
    else
      'square'
    end
  end
end

app/views/games/_space.html.erb
<style>
    .square {
        height: 100px;
        width: 100px;
        background-color: white;
        border: thick double #008000;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .square_bump {
        height: 100px;
        width: 100px;
        background-image: url("https://i.ibb.co/PGYX9Vq/image-12.png");
        display: flex;
        align-items: center;
        justify-content: center;
        background-size: 100px;
    }
    .square_move_back_3_cases {
        height: 100px;
        width: 100px;
        background-image: url("https://i.ibb.co/51Bhvxy/image-14.png");
        display: flex;
        align-items: center;
        justify-content: center;
        background-size: 100px;
    }
    .square_two_times {
        height: 100px;
        width: 100px;
        background-image: url("https://i.ibb.co/Ryt0LZk/image-13.png");
        display: flex;
        align-items: center;
        justify-content: center;
        background-size: 100px;
    }
    .square_hole {
        height: 100px;
        width: 100px;
        background-image: url("https://i.ibb.co/RPLtjqX/image-11.png");
        display: flex;
        align-items: center;
        justify-content: center;
        background-size: 100px;
    }

    .square_hole {
        height: 100px;
        width: 100px;
        background-image: url("https://i.ibb.co/RPLtjqX/image-11.png");
        display: flex;
        align-items: center;
        justify-content: center;
        background-size: 50px;
    }

    .red_player {
        height: 20px;
        width: 20px;
        background-image: url("https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pngitem.com%2Fso%2Fred-dot%2F&psig=AOvVaw3k7lxE3e-rarDSFlsr9GFe&ust=1622987215660000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCIjZodbQgPECFQAAAAAdAAAAABAO");
        display: flex;
        align-items: center;
        justify-content: center;
        background-size: 20px;
    }

    .number_position {
        flex-direction: column;
        align-self: flex-start;
    }
    .logo_for_special_cases {
        flex-direction: column;
        align-self: flex-end
    }

</style>


<div class="<%= display_icon(space.space_skill_id) %>">
  <div class="number_position">
    <%= space.position %>
  </div>
  <% unless @positions.empty? %>
    <% @positions.each do |position| %>
    <div class="">
      <% if position.space == space %>
        <%#= display_oie(@positions.first.player.color) %>
        <%= position.player.color %>
      <% end %>
    </div>
    <% end %>
  <% end  %>
</div>

app/views/games/show.html.erb
<style>
    .board {
        height: 300px; /* Or whatever */
    }
</style>
<% if @players.count == 0 %>
Tu attends quoi pour rentrer dans l'octogone ?!!! Let's gooooo clique moi ça <br />
  <% elsif @players.count == 1 %>
  Hey mais tu fais quoi là !! tu n'as pas de potes de l'apero ? Invite les desuite à rejoindre la partie !!!!!!! <br />
  <% elsif @players.count >= 2 %>
  Ok c'est bon je me calme... tu as des potes enfait et j'ai peur maintenant...
<% end %>
Voici le code d'invitation : <b><%= @game.invitation_code %></b> <br />
<%# if user_signed_in? %>
<%#= link_to "Sign out", destroy_user_session_path, method: :delete %>
<%# end %>
<% if @players.present? %>
  <br />
  Les participants sont : <br />
  <% @players.each do |player| %>
    - <%= player.user.name || player.user.email %> <br />
  <% end %>
<% end %>

<% if @player.id.nil? %>
  <%= form_for @player, url: players_path(@player), method: :post do |form| %>

    <div class="field">
      <%= form.label 'Quelle couleur voulait vous jouer ?' %> <br />
      <%= form.select :color, @game.color_available %><br />
      <%= form.hidden_field :invitation_code, value: @game.invitation_code %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
    <% end %>

<% end %>

<% if @finished %>
  La partie est terminée, le vainqueur est <%= @positions.map{|position| position.player.user.name || position.player.user.email if position.space.position == 63}.compact.join('') %> <br />
  <%= link_to "Cliquez ici pour revenir au menu principal !", end_game_path(id: @game ), method: :post %>
<% end  %>
<br />
<% if @game.status == Game::RUNNING && @credits.try(:amount).try(:positive?) && !@finished %>
  Vous avez <%= @credits.amount %> crédit(s), Good luck !
  <%= link_to "Roll the dices BRO !", rolls_path(credit: @credits, game: @game, player: @player ), method: :post %>
  <% else %>
  Vous n'avez pas de crédit !! Il faut conso là !!
<% end  %>
<br />
<br />
<% if @player.id.present? && @game.status == Game::WAITING && @game.players.count >= 2 %>
  <%= link_to "Start the game !", start_a_game_path( id: @game ), method: :post %>
<% elsif @game.status == Game::RUNNING %>

  <% else %>
  Il faut 2 joueurs minimum pour démarrer la partie
<% end  %>


    <div class="d-flex flex-wrap bd-highlight mb-3 align-content-center">
        <% @board.each do |space| %>
        <div class="p-2 bd-highlight " style="">
        <%= render partial: "games/space", locals: {space: space} %>
        </div>
        <% end %>
      </div>