config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'homepage#index'
  get 'homepage#index/:uuid' => 'homepage#index'

  # match "/patients/:id" => "patients#show"
  #
  # get 'homepage#index/:uuid' => 'homepage#index', :as => :root

  resources :games
  resources :players

  namespace :api do
    post 'events', to: 'events#receive_events'
  end

  post 'rolls', to: 'dices#rolls'
  post 'start_a_game', to: 'games#start_a_game'
  post 'end_game', to: 'games#end_game'

end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
  belongs_to :game
  has_many :game_credits, as: :personable, dependent: :delete_all
  has_many :player_space_positions, dependent: :delete_all

end

app/controllers/players_controller.rb
class PlayersController < InheritedResources::Base
  # before_action :set_game, only: [:create]
  before_action :authenticate_user!

  def new
    @player = Player.new
  end

  def create

    @player = Player::CreateFromInvitationCode.run(invitation_code: player_params[:invitation_code], user: current_user, color: player_params[:color])
    @game = Game.where(invitation_code: player_params[:invitation_code]).first

      if @player.success?
        redirect_to @game
      else

        redirect_to @game, notice: "Essayez encore ! "
      end

  end

  private

    def player_params
      params.require(:player).permit(:color, :game_id, :invitation_code)
    end

    def set_game
      @game = Game.find(params[:game_id])
    end


end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <%# if player.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2><%#= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>-->

<!--      <ul>-->
        <%# player.errors.full_messages.each do |message| %>
<!--          <li><%#= message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>
  Enter the invitation code :
  <% if params[:invitation_code] %>
  <div class="field">
    <%= form.label :invitation_code %>
    <%= form.text_field :invitation_code %>
  </div>
  <% else %>
  <div class="field">
    <%= form.text_field :invitation_code, value: params[:invitation_code] %>
  </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/create.html.erb
Enter the invitation code :

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Color</th>
      <th>User</th>
      <th>Game</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.color %></td>
        <td><%= player.user_id %></td>
        <td><%= player.game_id %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>Nouveau joueur</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @player.color %>
</p>

<p>
  <strong>User:</strong>
  <%= @player.user_id %>
</p>

<p>
  <strong>Game:</strong>
  <%= @player.game_id %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>